#!/usr/bin/env python3
"""Refresh the pinned, text-only Weibo mapping; never downloads image assets."""
import argparse
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EQUALMA_REF = '0e8520732ad7b8ca46dddf4dd87a7b5a09fdc1a4'
ITORR_REF = '4592e058d8931f144486b9c6009699113839aaea'


def fetch(repo, ref, path):
    url = f'https://raw.githubusercontent.com/{repo}/{ref}/{path}'
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read().decode('utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--equalma-ref', default=EQUALMA_REF)
    parser.add_argument('--itorr-ref', default=ITORR_REF)
    args = parser.parse_args()
    mapping = {}

    def add(label, url):
        if not isinstance(label, str) or not isinstance(url, str):
            return
        if not re.fullmatch(r'\[[^\[\]\r\n]{1,40}\]', label):
            return
        if not url.startswith(('http://', 'https://')):
            return
        mapping.setdefault(label, url.replace('http://', 'https://', 1))

    config = json.loads(fetch('EqualMa/weibo-emoji', args.equalma_ref,
                              'src/data/config-20251017.json'))
    for language in ['ZH_CN', 'ZH_TW']:
        for entries in config['data']['emoticon'][language].values():
            for item in entries:
                add(item['phrase'], item['url'])
    legacy = json.loads(fetch('EqualMa/weibo-emoji', args.equalma_ref,
                              'public/data.json'))
    for category in legacy['emoticon_format']:
        for item in category['value']:
            add(item['value'], item['url'])
    # The source entry is html/index.js; parse its literal map as JSON.
    # Do not execute downloaded JS. New official mappings take precedence.
    code = fetch('itorr/weibo-face', args.itorr_ref, 'html/index.js')
    base = re.search(r"const weiboFaceBaseURL\s*=\s*'([^']+)';", code)
    match = re.search(r'const WeiboFaces\s*=\s*(\{.*?\n\});', code, re.S)
    if base is None or match is None:
        raise ValueError('Upstream mapping format changed')
    for label, path in json.loads(match.group(1)).items():
        add(f'[{label}]', base.group(1) + path)

    def dart(value):
        return json.dumps(value, ensure_ascii=False).replace('$', r'\$')

    lines = [
        '// Generated by scripts/update_weibo_emoticons.py; do not hand-edit.',
        '// EqualMa/weibo-emoji (MIT): ' + args.equalma_ref,
        '// itorr/weibo-face (MIT), historical aliases: ' + args.itorr_ref,
        '// Image URLs only. Original image rights remain with their owners.',
        '// See THIRD_PARTY_NOTICES.md and third_party/licenses/MIT-*.txt.',
        '',
        'const weiboEmoticonUrls = <String, String>{',
        *[f'  {dart(label)}: {dart(url)},' for label, url in sorted(mapping.items())],
        '};',
        '',
    ]
    target = ROOT / 'lib/utils/source_rules/weibo_emoticon_data.dart'
    target.write_text('\n'.join(lines))
    for repo, ref, filename in [
        ('EqualMa/weibo-emoji', args.equalma_ref, 'MIT-weibo-emoji.txt'),
        ('itorr/weibo-face', args.itorr_ref, 'MIT-weibo-face.txt'),
    ]:
        (ROOT / 'third_party/licenses' / filename).write_text(fetch(repo, ref, 'LICENSE'))
    print(f'Generated {len(mapping)} names/aliases; no images downloaded.')


if __name__ == '__main__':
    main()
